### ISSUE TITLE
Followed instructions but got the following errors

### ISSUE THREAD

**Issue by sharmilhassan** [RuckerGauge/Raspberry-Pi-Zero-W-Bluez-5.50-upgrade-steps#1]
$ sudo gdbus introspect --system --dest com.netConfig --object-path / --recurse
"Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name com.netConfig was not provided by any .service files."

Then when executing this "node ./examples/sampleApp", I received the following errors at the end:

"advertisingClass.js | Calling RegisterAdvertisement on org.bluez...
adapterClass.js | Error with interface to 'org.bluez', /org/bluez/hci0, 'org.freedesktop.DBus.Properties'
Failed to request interface  Error: No introspectable
    at /home/pi/blePeripheral/node_modules/dbus/lib/bus.js:131:15
gattServiceClass.js | Error with interface to 'org.bluez', '/org/bluez/hci0', 'org.bluez.GattManager1'
Failed to request interface  Error: No introspectable
    at /home/pi/blePeripheral/node_modules/dbus/lib/bus.js:131:15
advertisingClass.js | Error with interface to 'org.bluez', '/org/bluez/hci0', 'org.bluez.LEAdvertisingManager1'
Failed to request interface  Error: No introspectable
    at /home/pi/blePeripheral/node_modules/dbus/lib/bus.js:131:15"

Could you please let me know what's wrong, thank you

**Comment by sharmilhassan** [comment]
I resolved this, thank you.
